version: "3.8"

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=*
    volumes:
      - chroma-data:/chroma/chroma

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./backend:/app
    restart: unless-stopped

volumes:
  chroma-data:
